---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic
  name: petclinic
  namespace: microservices-demo
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: petclinic
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic
  name: petclinic
  namespace: microservices-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - env:
        - name: OTEL_SERVICE_NAME
          value: petclinic
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector.monitoring:4318
        - name: OTEL_METRIC_EXPORT_INTERVAL
          value: '5000'
        - name: OTEL_METRICS_EXPORTER
          value: otlp
        - name: OTEL_LOGS_EXPORTER
          value: none
        - name: OTEL_TRACES_EXPORTER
          value: none
        - name: JDK_JAVA_OPTIONS
          value: -Xmx512m
        - name: JAVA_OPTS
          value: -Xmx131m
        image: ghcr.io/graz-dev/spring-petclinic-jdk25:0.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /owners/find
            port: 8080
          periodSeconds: 15
          timeoutSeconds: 5
        name: petclinic
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /owners/find
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 649m
            memory: 317Mi
          requests:
            cpu: 325m
            memory: 222Mi
        startupProbe:
          failureThreshold: 36
          httpGet:
            path: /owners/find
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
      nodeSelector:
        node-role: app
